apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-p3
  labels:
    app: app-p3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-p3
  template:
    metadata:
      labels:
        app: app-p3
    spec:
      containers:
        - name: app-p3
          image: juzzrespecter/inception_of_things_app:v2
          ports:
          - containerPort: 3000
