apiVersion: v1
type: Deployment
metadata:
  name: app-p3
  labels:
    app: app-p3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-p3
  templates:
    metadata:
      labels:
        app: app-p3
      spec:
        containers:
          - name: app-p3
            image: juzzrespecter:v1


